import type { APIRoute } from 'astro';
import { saveApplication } from '../../lib/applications';
import { sendApplicationEmails } from '../../lib/email';
import { supabase } from '../../lib/supabase';

export const POST: APIRoute = async ({ request, redirect }) => {
  try {
    const formData = await request.formData();
    
    const name = formData.get('name')?.toString();
    const email = formData.get('email')?.toString();
    const phone = formData.get('phone')?.toString();
    const jobSlug = formData.get('jobSlug')?.toString();
    const message = formData.get('message')?.toString() || '';
    const cvFile = formData.get('cv') as File;

    if (!name || !email || !phone || !jobSlug || !cvFile) {
      return new Response('Dados incompletos', { status: 400 });
    }

    // 1. Upload CV to Supabase Storage
    const fileExt = cvFile.name.split('.').pop();
    const fileName = `${Date.now()}_${Math.random().toString(36).substr(2, 9)}.${fileExt}`;
    const filePath = `${fileName}`;

    const { data: uploadData, error: uploadError } = await supabase.storage
        .from('cvs')
        .upload(filePath, cvFile, {
            cacheControl: '3600',
            upsert: false
        });

    if (uploadError) {
        console.error('Erro no upload:', uploadError);
        return new Response('Erro ao fazer upload do ficheiro', { status: 500 });
    }

    // 2. Save Application Data to Supabase DB
    // Note: cvPath is now the path in storage (e.g. "dirname/filename.pdf") or we can use the served API URL.
    // We will stick to the API proxy URL pattern "/api/cv/[path]" so existing links work, 
    // OR simply store the storage path and let the API resolve it.
    // Let's store the storage path, and have /api/cv/[id] resolve it.
    // Actually, let's allow direct download via a secure link if possible, or keep the proxy.
    // Keeping proxy is better for consistent URLs: /api/cv/filename
    
    const appData = {
        jobSlug,
        name,
        email,
        phone,
        message,
        cvPath: filePath, // Storing the filename/path in bucket
        // submittedAt is auto-generated by DB default
    };

    await saveApplication(appData);

    // 3. Send Emails
    // We pass a reconstructed object because saveApplication usually returns nothing or just confirmation.
    // We might need the date for the email.
    const emailData = {
        ...appData,
        id: 'generated-by-db', // placeholder or we fetch it back
        submittedAt: new Date().toISOString(),
        cvPath: `/api/cv/${filePath}` // This will be the link in the email
    };

    sendApplicationEmails(emailData).catch((err: unknown) => console.error('Erro ao enviar email:', err));

    return redirect('/recrutamento/confirmacao', 303);
    
  } catch (error) {
    console.error('Erro ao processar candidatura:', error);
    return new Response('Erro interno do servidor', { status: 500 });
  }
};
